### PR TITLE
Add otherworldly items

### PR DESCRIPTION
**Pull request by tegstewart**
Adds items from http://www.dolserver.net/viewtopic.php?f=63&t=23174

### CODE REVIEW

**Comment by LRFalk01** [comment]
@tegstewart CI error:
Duplicate entry 'glowing_dreaded_seal' for key 'PRIMARY'

Looks like the error is in this file:
/customizations/ServerType.PVE.DreadedSeals.sql

**Comment by tegstewart** [comment]
Reapplied the queries to a fresh DB.

**Comment by tegstewart** [comment]
I don't think Travis is going to be of much help here.

**Comment by LRFalk01** [comment]
I can't update this branch. I don't suppose you can re-PR this?

**Comment by tegstewart** [comment]
Will do.  Pesky thing.

**Pull request closed without merging**
