### PR TITLE
Add table definitions in code

### PR DESCRIPTION
**Pull request by NetDwarf**
Remove corresponding sql files
Replace usage of sql files with built-in tables

### CODE REVIEW

**Comment by NetDwarf** [comment]
This is supposed to be a refactoring with no behavior changes, however of course I had to make some concessions; namely:
- white space differences
- some types for SQLite are different
- I had to add another exportignore (`Minotaurrelic`), because I changed to precise match (case-insensitive) and previously it was matched by `Relic` alone which was probably not intended
- added a missing table in SQLite (`server_category`)

Regarding the SQLite types, these are still inside the broad types that SQLite actually exposes to the user (`NULL`, `INTEGER`, `REAL`, `TEXT`, `BLOB`)[¹](https://www.sqlite.org/datatype3.html). So it should also not change anything.

The `diff` is still rather small from this to the previous exported sqls and it is easy to track by eye.

**Review by LRFalk01 — COMMENTED** [review]
The goal here is to not define mostly duplicate tables for both sqlite and mysql, yes? I think probably an approach more in line with how the data is orchestrated would have been to define the tables as json with a jsonschema to enforce your convention. That being said, I dont dislike this 😂. Let me know when you're happy with this PR, and I'll get it merged.

**Comment by NetDwarf** [comment]
The goal is to have an SQL agnostic table definition. JSON has the disadvantage of being very lengthy and harder to maintain/alter. i.e. 
```
t := newTable("Ability")
t.Static = true
t.AddPrimary("AbilityID", "int(11)").NotNullable()
```
in JSON:
```
[
  "Ability": {
    "Static" : true
    "Primary" : "AbilityID"
    "Columns" : [
      "AbilityID" : {
        "Type" : "int(11)"
        "NotNull" : true
      }
    ]
  }
]
```

And that was just one column.

The code definition also has the advantage that it is augmented by the IDE. 

That being said. JSON would have the advantage that it's easier to add/import arbitrary tables, but this is not (yet) a goal, but it's an option for sure. The code implementation can also be tweaked, but I thought I better PR the working state instead of trying to perfect it and then just not PRing it at all.

In a way I am happy with this PR and am going to tweak the output next.

**Review by LRFalk01 — APPROVED** [review]

**Pull request merged**
