### PR TITLE
Killaloe BG : add items to merchant for each realm

### PR DESCRIPTION
**Pull request by DigitalBox98**
Addition of items on each merchant + Spell for proc + Various things 

Albion
Weapons : Alb_Killaloe_Longsword, Alb_Killaloe_Spiked_Mace, Alb_Killaloe_Rapier, Alb_Killaloe_Shortsword, Alb_Killaloe_Mace, Alb_Killaloe_Dagger, Alb_Killaloe_Whip, Alb_Killaloe_Flail, Alb_Killaloe_Claymore, Alb_Killaloe_Great_Hammer, Alb_Killaloe_War_Pick, Alb_Killaloe_Halberd, Alb_Killaloe_Mystic_Staff, Alb_Killaloe_Quarterstaff, Alb_Killaloe_Weighted_Staff, Alb_Killaloe_Fist_Wrap, Alb_Killaloe_Longbow, Alb_Killaloe_Shortbow, Alb_Killaloe_Crossbow, Alb_Killaloe_Large_Shield, Alb_Killaloe_Medium_Shield, Alb_Killaloe_Small_Shield, Alb_Killaloe_Harp

Armors : Alb_Killaloe_Cloth_Robe, Alb_Killaloe_Cloth_Sleeves, Alb_Killaloe_Cloth_Leggings, Alb_Killaloe_Cloth_Cap, Alb_Killaloe_Cloth_Gloves, Alb_Killaloe_Cloth_Boots, Alb_Killaloe_Leather_Tunic, Alb_Killaloe_Leather_Sleeves, Alb_Killaloe_Leather_Leggings, Alb_Killaloe_Leather_Helmet, Alb_Killaloe_Leather_Gloves, Alb_Killaloe_Leather_Boots, Alb_Killaloe_Studded_Tunic, Alb_Killaloe_Studded_Sleeves, Alb_Killaloe_Studded_Leggings, Alb_Killaloe_Studded_Helmet, Alb_Killaloe_Studded_Gloves, Alb_Killaloe_Studded_Boots, Alb_Killaloe_Chain_Chestpiece, Alb_Killaloe_Chain_Sleeves, Alb_Killaloe_Chain_Chausses, Alb_Killaloe_Chain_Helm, Alb_Killaloe_Chain_Gloves, Alb_Killaloe_Chain_Boots, Alb_Killaloe_Plate_Chestplate, Alb_Killaloe_Plate_Sleeves, Alb_Killaloe_Plate_Chausses, Alb_Killaloe_Plate_Helm, Alb_Killaloe_Plate_Gloves, Alb_Killaloe_Plate_Greaves, 

Jewels : Alb_Killaloe_Mystic_Necklace, Alb_Killaloe_Mighty_Necklace, Alb_Killaloe_Shrouded_Necklace, Alb_Killaloe_Cloak, Alb_Killaloe_Mystic_Gemstone, Alb_Killaloe_Mighty_Gemstone, Alb_Killaloe_Shrouded_Gemstone, Alb_Killaloe_Belt, Alb_Killaloe_Ring, Alb_Killaloe_Bracer, Alb_Killaloe_Defender_Arcane, Alb_Killaloe_Defender_Magic, Alb_Killaloe_Defender_Mighty, Alb_Killaloe_Defender_Curative, Alb_Killaloe_Defender_Variant, Alb_Killaloe_Defender_Enduring, Alb_Killaloe_Defender_Stalwart, Alb_Killaloe_Defender_Focal

Hibernia:
Weapons : Hib_Killaloe_Longsword, Hib_Killaloe_Spiked_Mace, Hib_Killaloe_Rapier, Hib_Killaloe_Shortsword, Hib_Killaloe_Mace, Hib_Killaloe_Dagger, Hib_Killaloe_Great_Sword, Hib_Killaloe_Great_Hammer, Hib_Killaloe_Celtic_Spear, Hib_Killaloe_Scythe, Hib_Killaloe_Arch_Mace, Hib_Killaloe_Mystic_Staff, Hib_Killaloe_Weighted_Staff, Hib_Killaloe_Fist_Wrap, Hib_Killaloe_Large_Shield, Hib_Killaloe_Medium_Shield, Hib_Killaloe_Small_Shield, Hib_Killaloe_Recurse_Bow, Hib_Killaloe_Shortbow, Hib_Killaloe_Harp

Armors : Hib_Killaloe_Cloth_Robe, Hib_Killaloe_Cloth_Sleeves, Hib_Killaloe_Cloth_Leggings, Hib_Killaloe_Cloth_Cap, Hib_Killaloe_Cloth_Gloves, Hib_Killaloe_Cloth_Boots, Hib_Killaloe_Leather_Tunic, Hib_Killaloe_Leather_Sleeves, Hib_Killaloe_Leather_Leggings, Hib_Killaloe_Leather_Helmet, Hib_Killaloe_Leather_Gloves, Hib_Killaloe_Leather_Boots, Hib_Killaloe_Studded_Tunic, Hib_Killaloe_Studded_Sleeves, Hib_Killaloe_Studded_Leggings, Hib_Killaloe_Studded_Helmet, Hib_Killaloe_Studded_Gloves, Hib_Killaloe_Studded_Boots, Hib_Killaloe_Chain_Chestpiece, Hib_Killaloe_Chain_Sleeves, Hib_Killaloe_Chain_Chausses, Hib_Killaloe_Chain_Helm, Hib_Killaloe_Chain_Gloves, Hib_Killaloe_Chain_Boots

Jewels : Hib_Killaloe_Mystic_Necklace, Hib_Killaloe_Mighty_Necklace, Hib_Killaloe_Shrouded_Necklace, Hib_Killaloe_Cloak, Hib_Killaloe_Mystic_Gemstone, Hib_Killaloe_Mighty_Gemstone, Hib_Killaloe_Shrouded_Gemstone, Hib_Killaloe_Belt, Hib_Killaloe_Ring, Hib_Killaloe_Bracer, Hib_Killaloe_Defender_Arcane, Hib_Killaloe_Defender_Magic, Hib_Killaloe_Defender_Mighty, Hib_Killaloe_Defender_Curative, Hib_Killaloe_Defender_Variant, Hib_Killaloe_Defender_Enduring, Hib_Killaloe_Defender_Stalwart, Hib_Killaloe_Defender_Focal

Midgard
Weapons : Mid_Killaloe_Longsword, Mid_Killaloe_WarHammer, Mid_Killaloe_WarAxe, Mid_Killaloe_LeftAxe, Mid_Killaloe_MoonFang, Mid_Killaloe_ClawGreave, Mid_Killaloe_Spear, Mid_Killaloe_Great_Sword, Mid_Killaloe_Great_Hammer, Mid_Killaloe_Great_Axe, Mid_Killaloe_Arch_Hammer, Mid_Killaloe_Runic_Hammer, Mid_Killaloe_Mystic_Staff, Mid_Killaloe_Weighted_Staff, Mid_Killaloe_Fist_Wrap, Mid_Killaloe_Large_Shield, Mid_Killaloe_Medium_Shield, Mid_Killaloe_Small_Shield, Mid_Killaloe_Composite_Bow, Mid_Killaloe_Shortbow

Armors : Mid_Killaloe_Cloth_Tunic, Mid_Killaloe_Cloth_Sleeves, Mid_Killaloe_Cloth_Leggings, Mid_Killaloe_Cloth_Cap, Mid_Killaloe_Cloth_Gloves, Mid_Killaloe_Cloth_Boots, Mid_Killaloe_Leather_Tunic, Mid_Killaloe_Leather_Sleeves, Mid_Killaloe_Leather_Leggings, Mid_Killaloe_Leather_Helmet, Mid_Killaloe_Leather_Gloves, Mid_Killaloe_Leather_Boots, Mid_Killaloe_Studded_Tunic, Mid_Killaloe_Studded_Sleeves, Mid_Killaloe_Studded_Leggings, Mid_Killaloe_Studded_Helmet, Mid_Killaloe_Studded_Gloves, Mid_Killaloe_Studded_Boots, Mid_Killaloe_Chain_Chestpiece, Mid_Killaloe_Chain_Sleeves, Mid_Killaloe_Chain_Chausses, Mid_Killaloe_Chain_Helm, Mid_Killaloe_Chain_Gloves, Mid_Killaloe_Chain_Boots

Jewels : Mid_Killaloe_Mystic_Necklace, Mid_Killaloe_Mighty_Necklace, Mid_Killaloe_Shrouded_Necklace, Mid_Killaloe_Cloak, Mid_Killaloe_Mystic_Gemstone, Mid_Killaloe_Mighty_Gemstone, Mid_Killaloe_Shrouded_Gemstone, Mid_Killaloe_Belt, Mid_Killaloe_Ring, Mid_Killaloe_Bracer, Mid_Killaloe_Defender_Arcane, Mid_Killaloe_Defender_Magic, Mid_Killaloe_Defender_Mighty, Mid_Killaloe_Defender_Curative, Mid_Killaloe_Defender_Variant, Mid_Killaloe_Defender_Enduring, Mid_Killaloe_Defender_Stalwart, Mid_Killaloe_Defender_Focal

### CODE REVIEW

**Comment by NetDwarf** [comment]
image

:sweat_smile:

**Comment by DigitalBox98** [comment]
I notice that too. Not sure about the reason it will not display at least the files list.

**Comment by NetDwarf** [comment]
I think this has two reasons.
1.) Not imported with newest binary (`-import` algorithm changed)
2.) git seems to have an issue properly patching ItemTemplate (judging from primary key order with only additions and no removal)

The second is benign I think.

**Comment by NetDwarf** [comment]
For the 2.) reason there is a small correction. It's a matter of which diff-algorithm is used. The default one shows a lot of changes for actually 16038 added lines as follow:
`> git diff --numstat upstream/master`
image
`> git diff --diff-algorithm=minimal --numstat upstream/master`
image

So, everything is fine after 1.) is corrected.

**Comment by DigitalBox98** [comment]
I was not aware public-db-tools was changed. 
So I need to relaunch it again and submit the corresponding files ?

**Comment by NetDwarf** [comment]
> I was not aware public-db-tools was changed. So I need to relaunch it again and submit the corresponding files ?

Yeah if you haven't changed anything in database you can just `-import` with the new binary and be done with it. You could use the previous commands/results as sanity check.

**Comment by DigitalBox98** [comment]
Ok done : )

**Comment by NetDwarf** [comment]
@LRFalk01 Yeah, everything is fine:

image

**Review by LRFalk01 — APPROVED** [review]

**Comment by DigitalBox98** [comment]
Cool :)

**Pull request merged**
