### PR TITLE
Spells from token : fix tooltip id

### PR DESCRIPTION
**Pull request by DigitalBox98**
Some tooltip id weren't correct for the Token Spells

### CODE REVIEW

**Comment by DigitalBox98** [comment]
Not sure about the results as I'm using /cast loadspell <id> and /cast spell <id> to test the tooltips, but it seems after reloading the DB, the tooltips are not the same than during the tests :/

**Comment by NetDwarf** [comment]
> Not sure about the results as I'm using /cast loadspell and /cast spell to test the tooltips, but it seems after restarting the server and reloging that the tooltips are not the same than during the tests :/

Beware that tooltips (for 1.110+ clients) are cached (in Documents folder iirc).

**Comment by DigitalBox98** [comment]
Ok I've got 3 remaining tooltips not correct, however even when removing delve.txt and relogging the results are different than when restarting the server. 
Not easy task I will double check :)

**Comment by DigitalBox98** [comment]
Ok tooltipids are now made unique and all is OK :)

**Review by LRFalk01 — APPROVED** [review]

**Pull request merged**
