### PR TITLE
Gui enhancements

### PR DESCRIPTION
**Pull request by tegstewart**
Two cosmetic things, and one time saver.

### CODE REVIEW

**Comment by LRFalk01** [comment]
I'm not 100% on this PR, tbh. I'm waiting for Ben to talk about it. I think Enhancements is kind of questionable name. Customizations would be a more accurate title. The RP should be rebased to not be 8 commits. (9 commits if we change the directory name)

**Comment by tegstewart** [comment]
As long we have something reasonably intuitive, where it goes doesn't matter to me.

I'm certainly going to come up with more as time goes by, so if you prefer I can wait until I have a big pile of them and do them all at once.

**Comment by LRFalk01** [comment]
We agree that the directory should be named Customizations. Could you update the name and squash your commits?

**Comment by benfalk** [comment]
These scripts are fine; however, I agree that it should probably be called `customization`

From the Google:
  - *customization* : the action of modifying something to suit a particular individual or task. 
  - *enhancement* : an increase or improvement in quality, value, or extent.

While the scripts certainly are each a customization; it could be argued that each being an enhancement is more of an opinion.

**Comment by benfalk** [comment]
If you need help squishing these commits let me know 👍

**Comment by tegstewart** [comment]
Sounds good.  I'll change the folder name and do it as a single commit.

**Pull request closed without merging**
