### PR TITLE
First Round of duplicate Item purging

### PR DESCRIPTION
**Pull request by LRFalk01**
I grouped items by name and realm then found the items that were matches based on 14 fields (Level, DPS_AF, SPD_ABS, Type_Damage, Object_Type, Item_Type, Bonus[0-5], SpellID, and SpellID1). This is the removal of all items finding to be exact matches where their id ends in a number and they have a matching partner with the same Id_nb minus the number. 3441 ItemTemplates removed and updated MerchantItem/LootTable entries accordingly.

### CODE REVIEW

**Comment by tegstewart** [comment]
Does this also include the new items from the official DB?

**Comment by LRFalk01** [comment]
No. This is just purging duplicate items I have another ~1030 items that are as far as I can tell pure duplicates. This is all to make it easier to cleanup the actual items.
+

**Comment by OntheDOL** [comment]
could be an issue here with crafting too, as crafting materials more often than not are <Id_nb>2/3

**Comment by LRFalk01** [comment]
Why is this true? Can We just fix the material cost as well?

**Comment by OntheDOL** [comment]
yes well just means we need to change all the recipes in crafteditem/xitem to match
for mid, yes, as they use the same recipes as alb, but hibs use different recipes ( different metal/cloth for example) so they need a separate recipe, which means a duplicate item (only the item being crafted, not the materials)

**Comment by LRFalk01** [comment]
I didn't de-dupe separate realms if these hib crafted items were in their realm, there shoudlnt be an issue. I'll look into it.

**Comment by OntheDOL** [comment]
Mon_gem3 for example, is used in all the hib spellcrafting recipes, so if it no longer exists , there is issue

**Comment by LRFalk01** [comment]
I think the issue is that there is a hib specific item marked at realm 0. Updating the crafting tables will fix this mon3 issue.

**Pull request merged**
