### PR TITLE
MacOS : fix binaries format

### PR DESCRIPTION
**Pull request by DigitalBox98**
Format is now correct with Mach-O 64-bit executable x86_64

### CODE REVIEW

**Comment by LRFalk01** [comment]
Does something need changed in the script that generates the executables?

**Comment by DigitalBox98** [comment]
I don't think so : launching these scripts on MacOS is generating the good binaries format
So I guess if the scripts are launched on another platform it's not the same result (not sure where it comes from)

**Comment by LRFalk01** [comment]
I think this is just because MacOS is dumb. Generating the binaries on any platform for Win/Linux works fine. I guess the better option here is to just remove the macos binaries from source control and have the user generate them manually. A better option would be for the user to use a better OS that isn't so bad like Ubuntu. :trollface:

**Comment by DigitalBox98** [comment]
Ok and the windows binaries were generated from windows or Linux ? If it was Windows so MacOS behave the same way than other OS :)
I’m not an expert with GO building, but it seems there’s a gox command for cross compilation:
gox -osarch="darwin/amd64 linux/386 linux/amd64"
So it might be a point to investigate

**Comment by LRFalk01** [comment]
We've generated the binaries on both windows and linux, and have ran them on the other platform. I don't have a personal macos device to play around with it. I use a mac for work but I'd never use it after hours when I dont have to 😂

**Comment by NetDwarf** [comment]
This idea might be stupid, but would it be an option to generate binaries via Github Actions? Afaik it's free for open-source projects and it supports Linux, Windows and macOS.

**Comment by LRFalk01** [comment]
That's probably a pretty good idea, tbh.

**Comment by LRFalk01** [comment]
It removes the concern I have with a nefarious actor generating a compromised binary.

**Comment by DigitalBox98** [comment]
Agree with the Mac not after hours :)

I've double checked the script "compile_sripts.sh" and it seems an export is missing :
# Compile Macos
export GOOS=darwin
export GOARCH=amd64

The same fix should apply for Windows and Linux section so that cross compilation can occur whatever the platform is Win/Mac/Linux  :)

**Comment by DigitalBox98** [comment]
It should be OK now with the script changes:)
If this PR is a mess, I can create another one, let me know.

**Comment by LRFalk01** [comment]
it looks like your branch is out of date of current master. every file is in conflict.

**Comment by DigitalBox98** [comment]
Yes hence my remark. I will recreate a clean PR.

**Pull request closed without merging**
