### PR TITLE
fix autostat npctemplates

### PR DESCRIPTION
**Pull request by OntheDOL**
for autostat to work, the code looks at template to have all stat values at '0' . If one has a value other than this, mob will be created with those stats, including the 0's . Fixes mobs with 1Hp or rediculously low HP for their level

### CODE REVIEW

**Comment by tegstewart** [comment]
I don't like this one.

We should be able to have a mob with higher strength but default everything else by setting it to zero.  Code doesn't currently work that way, but that's an issue with code, not an issue with the DB.

**Comment by OntheDOL** [comment]
well, it also fixes all the mobs with low strength stats too. Autostats is set in regards to how the current melee code works. You will find red mobs that you can solo because their strength value is set too low. To be honest, every template on here should be set to '0' for all stats, and then individual stats for certain templates set from there

**Comment by tegstewart** [comment]
That messes up some of the scarier epic style mobs.  Maybe we should be doing a check for strength values in the DB that are set too low?

**Comment by tegstewart** [comment]
I just submitted a PR to DOLSharp to fix how mob stats are calculated.

That will likely impact which mobs are too easy, since things like an npctemplate defining a higher Qui or Con or something won't cause Str to be set to 0.

**Pull request closed without merging**
