### PR TITLE
Add OldArchery

### PR DESCRIPTION
**Pull request by NetDwarf**
This was previously hardcoded in the server

### CODE REVIEW

**Review by LRFalk01 — APPROVED** [review]

**Review by Dorinakka — COMMENTED** [review]
[
		{
			"AbilityKey": "Volley",
			"AbilityLevel": 1,
			"ClassId": 0,
			"LastTimeRowUpdated": "1999-01-01 00:00:00"
			"Spec": "OldArchery",
			"SpecLevel": 35,
			"SpecXabilityID": 383,
		},
		{
			"AbilityKey": "Volley",
			"AbilityLevel": 2,
			"ClassId": 0,
			"LastTimeRowUpdated": "1999-01-01 00:00:00"
			"Spec": "OldArchery",
			"SpecLevel": 40,
			"SpecXabilityID": 384,
		},
		{
			"AbilityKey": "Volley",
			"AbilityLevel": 3,
			"ClassId": 0,
			"LastTimeRowUpdated": "1999-01-01 00:00:00"
			"Spec": "OldArchery",
			"SpecLevel": 45,
			"SpecXabilityID": 385,
		},
		{
			"AbilityKey": "Volley",
			"AbilityLevel": 4,
			"ClassId": 0,
			"LastTimeRowUpdated": "1999-01-01 00:00:00"
			"Spec": "OldArchery",
			"SpecLevel": 50,
			"SpecXabilityID": 386,
		}
	]
}

**Comment by LRFalk01** [comment]
I'm not sure what you're trying to convey here, @Dorinakka

**Comment by Dorinakka** [comment]
@LRFalk01 sorry, entered wrong. shouldn't do that if i don't have time. I hope it's correct now?

**Pull request merged**
