### PR TITLE
Camelot hills npc add

### PR DESCRIPTION
**Pull request by Nachtmahr91**
The following NPCs have been added because they were missing for quests or simply because of the optics.

Sir Prescott
Sir Sagramore
Scholar Akimi
Pompin the Crier
Commander Kerlean

### CODE REVIEW

**Comment by LRFalk01** [comment]
@Nachtmahr91 your PR is out of sync with master I do not have access to fix this within your branch for you

```Merging via command line

Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b Nachtmahr91-Camelot-Hills-NPC-Add master
git pull https://github.com/Nachtmahr91/db-public.git Camelot-Hills-NPC-Add

Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff Nachtmahr91-Camelot-Hills-NPC-Add
git push origin master```

**Comment by Nachtmahr91** [comment]
I hope it works now. ;)

**Comment by LRFalk01** [comment]
@Nachtmahr91 We've tried to pull your branch locally to update it and create a new PR, but this branch is 23 commits behind master. You're going to have to redo it after you have newest from origin/master.

**Comment by benfalk** [comment]
23-commits-behind

**Pull request closed without merging**
